### PR TITLE
No reboot after toggle

### PR DESCRIPTION
**Pull request by hamzahrmalik**
App has a UI which has a switch
After toggling switch, app kills background processes
System UI is killed using SU

### CODE REVIEW

**Comment by GermainZ** [comment]
I can't accept this for several reasons:
- All the Eclipse config files are unnecessary, please don't include them in your commit. You can edit .gitignore if you want to ignore them (please make a separate commit in that case, "Update .gitignore"), or manually keep them out of your commit. Also, please keep the Xposed API JAR out, I don't include it so people always get the latest version.
- styles.xml is unnecessary. You're not even adding anything to Holo.Light, so why not use it directly (also see two points below)?
- What's hello_world?
- I don't understand why you're using an Activity (with its own custom layout) instead of using a simple PreferenceActivity. This would also get rid of the save button which is redundant.
- Please use a separate name for the activity, and keep Hodor.java intact.
- Please keep the hook in initZygote. I realize you changed it so you can ignore the settings activity, but I think that's part of the fun. Hodor.

Thanks!

**Comment by hamzahrmalik** [comment]
1) Ok
2) Ok
3) Added automatically by Eclipse when creating Activity - will fix
4)I honestly don't know - will fix
5) Yeah was an accident as i said, i can fix it
6) Ok then, dont blame me if people can't switch it off ;)

**Comment by hamzahrmalik** [comment]
is there a reason you're building with 4.3?
Can i change to 4.4.4?
EDIT
also it has to be in hookLoadPackage so it will make the hook again when restarting packages

**Comment by GermainZ** [comment]
targetSdkVersion = 19 = KitKat. Not sure what you're talking about.

**Comment by hamzahrmalik** [comment]
When i right click in Eclipse > Properties > Android 4.3 is ticked
Screenshot: http://puu.sh/9VlzK/8f674bc015.png

**Comment by GermainZ** [comment]
I don't use Eclipse, but that looks like the way you've configured Eclipse's defaults… nothing to do with this project.

**Comment by hamzahrmalik** [comment]
It was like that when i imported..never mind no worries i changed it
I've nearly fixed the rest too

**Comment by GermainZ** [comment]
Some more issues I see:
- I don't see why you're using `handleLoadPackage` - all that code can be in `initZygote`. Also, the lines that are commented out can be entirely removed.
- Don't forget to remove unused imports.
- Continuing the use of Hodor variables in Hodor.java, consider replacing `KEY_ENABLED` with something like `HODOR_HODOOOOR`. Also, there's no need to separate it from the other variable declarations.
- `c = this.getApplicationContext()` It's an Activity… just use "this" when you need a context…
- Sometimes you use spaces. Sometimes you use tabs. Sometimes you use 4 spaces to indent, sometimes 3, sometimes -4, etc. Please be consistent with the rest of the code (4 spaces to indent).
- Please keep the original formatting for e.g. this line: `android:versionName="1.0">`, keep the line break before the meta-data, etc, for consistency.
- The blank lines are also confusing. Sometimes you put one after a bracket, sometimes before, sometimes both, sometimes none at all. Again, please be consistent… I usually use none in these cases because it's an unnecessary, non logical break.
- I'm not sure if getting the list of all installed packages is necessary to kill them. Wouldn't `getRunningAppProcesses` work?
- `getPreferenceScreen().getSharedPreferences().registerOnSharedPreferenceChangeListener(this);` can probably use `implements OnSharedPreferenceChangeListener` here instead.
- `this.getPreferenceManager().setSharedPreferencesName(PREF);` I might be missing something, but why set a name explicitly? The default is "packagename_preferences" so we could just use that (in a `static final String`).
- .settings/org.eclipse.jdt.core.prefs shouldn't be committed.
- Finally, please squash your commits.

Sorry for so many issues, but most are just about being consistent with the rest of the code, which is very important. Thanks. :)

**Comment by hamzahrmalik** [comment]
No problem 
I'm using handleloadpackage because as far as I know (I might be wrong) initZygote is only called once when system starts so te switch wouldn't work 
I'm using an explicit context because I need it in the nested class. I can't remember where I'm not at PC
Not sure what you mean about implementing onSharedPreferenceListener
I will fix the rest, the formatting is due to copy and pasting my bad

**Comment by GermainZ** [comment]
> I'm using handleloadpackage because as far as I know (I might be wrong) initZygote is only called once when system starts so te switch wouldn't work

It doesn't matter (the hook gets executed when the method is called, that's what matters).

> Not sure what you mean about implementing onSharedPreferenceListener

Ah, never mind, I read that wrong.

(Also, a quick reminder to please squash your commits once you're done. Thanks!)

**Comment by hamzahrmalik** [comment]
Just to double check, all I need to do is move code to initzygote?

**Comment by GermainZ** [comment]
> Just to double check, all I need to do is move code to initzygote?

Yes, that should be enough.

BTW, I'm not sure if you're done or not, but indentation is still inconsistent (spaces/tabs) and some things aren't properly indented yet.

**Comment by hamzahrmalik** [comment]
Aren't they...
Will check

**Comment by hamzahrmalik** [comment]
Everything should be done
Not sure how to squash...will look it up later

**Comment by hamzahrmalik** [comment]
Ok, everything is done and squashed into one commit

**Comment by hamzahrmalik** [comment]
The mod no longer works after moving to initzygote

**Comment by GermainZ** [comment]
> Ok, everything is done and squashed into one commit

Some things still aren't indented (or are over indented). Also, please edit the commit message to make it general (e.g. "Add option to toggle module without restarting" instead of "no reboot after toggle").

> The mod no longer works after moving to initzygote

That's because you're only _hooking_ if the switch is enabled. Instead, put the check _inside_ the hook.

**Comment by hamzahrmalik** [comment]
everything should be done now
I formatted using Eclipse (ctrl shift f)
I've tested an it works fine for me (Android 4.0.4)

**Comment by GermainZ** [comment]
Sorry for the late reply, didn't have time until now. The pull request looks good except for one thing: please use spaces instead of tabs:

> Please be consistent with the rest of the code (4 spaces to indent).

(Also, please squash the commits again once you do that.)

**Comment by hamzahrmalik** [comment]
I used Eclipse to format the WHOLE code automatically. It should all be fine

**Comment by GermainZ** [comment]
Yes, it uses tabs everywhere now, but it should use spaces everywhere instead. That's the way it was before, and I personally prefer spaces over tabs. Thanks.

**Pull request closed without merging**
